### ISSUE TITLE
Customize OpenAPI Schema

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#131]
## Use the following framework for 
- [ ] Cicero API
- [ ] Lob API
- [ ] Auth0 API

## Context: 
Here’s a good [basic structure](https://swagger.io/docs/specification/basic-structure/) documentation site, but the [official specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#oasObject) is pretty easy to follow.

The root file must contain a few objects:
- The root [OpenAPI object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#oasObject) which also contains a [general Info ](https://swagger.io/docs/specification/api-general-info/)object that contains a title, version, licensing, contact information, and a link to the Pages site (externalDocs), also ToS or other stuff.
[Server URL/base path](https://swagger.io/docs/specification/api-host-and-base-path/) configuration
- And then each API has paths /root/user and those paths have actions root/user/get

We probably want to have as many re-usable parts as possible. We should define a list of them, but there are definitely a few that leap to mind:
- [Schemas](https://swagger.io/specification/#schema-object) - contain the reusable ones in one place, like Address, every API probably needs the user’s address, or username.
- [Responses](https://swagger.io/specification/#response-object) - generic “success” or “404” or other messages we don’t want to write out 5000 times
- Error - something went wrong and we don’t know what. Used when other, specifically written error messages do not apply. (case-else)

- What to we need to know if we need to define a security scheme ([authentication/authorization](https://swagger.io/docs/specification/authentication/)), or if we’re even using any - that might be handled completely elsewhere, like by GitHub itself?
- Documentation should cover any HTTP error [responses](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#responses-object) that are likely to happen and include instructions on how to remedy it and the “200 success” code.
- The APIs we are using, not writing, may have their own OpenAPI files already available, so we can potentially copy their stuff into our stuff rather than write it all up from scratch. Not sure what the plan is to keep all that up to date, though. If they change their stuff that we rely on, how do we know?

This template doesn’t include complete coverage of all possible OpenAPI fields, but it’s useful as starter code. In most cases you’ll want to add your own response schemas and reusable components. You can dig into the [OAS specification](https://github.com/OAI/OpenAPI-Specification) itself or see our OpenAPI and Swagger examples below.

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0 // Version of your API
  title: Your API Title
  description: An API description template
  contact:
    name: Your Name
    email: email@example.com
    url: http://example.com
  license:
    name: License Name
    url: http://example.com/license-url
servers:
  - url: http://api.example.com
paths:
  /your_endpoint:
    get:
      description: |
        Multi-line description
        of your API endpoint
      operationId: yourOperation
      parameters:
        - name: your_param
          in: query
          description: Description of your param
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Your success description
```

**Comment by therzka** [comment]
closing in favor of https://github.com/ProgramEquity/amplify/issues/125
