### ISSUE TITLE
Bug: Awkward word-wrapping for campaign names

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#150]
Some of the newer campaigns we've added for Sunrise have longer names. Some of these are exhibiting some awkward word-wrapping, e.g.:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/417751/159747842-dd297e80-838c-47a6-833c-ae7e5f585cef.png">

It would be ideal if we could avoid that. ✨

**Comment by manishapriya94** [comment]
@nawazkhan @nawazeverlane

**Comment by manishapriya94** [comment]
@hussam-i-am good first issue, let @mahrsbar or @nawazkhan know if you need any pointers. 
- Data structures listed [here](https://github.com/ProgramEquity/amplify/discussions/62#discussioncomment-2128538)
- File component to change [here](https://github.com/ProgramEquity/amplify/blob/main/src/components/CampaignCards.vue)

**Comment by mariah622** [comment]
I'd like to work on this! I haven't been officially assigned an issue but this one was one of the potential ones mentioned on Wednesday's PP hours

**Comment by mariah622** [comment]
#239

**Comment by mariah622** [comment]
Awkward Word Wrapping Fix #239

**Comment by mariah622** [comment]
Issue has been resolved successfully with the above merged pr.
