### ISSUE TITLE
Bug: "Breathe Act" letter contains duplicate content

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#151]
It looks like the Lob template content for the "Breathe Act" letter contains duplicate content:

<img width="683" alt="Screen Shot 2022-03-23 at 11 50 26 AM" src="https://user-images.githubusercontent.com/417751/159753044-29357165-70fa-4478-b94d-10993efbdf54.png">

We should clean that up on the Lob side. 🧹

**Comment by manishapriya94** [comment]
fixed!
