### ISSUE TITLE
Epic 2: Securing current workflows

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#158]
## Description
Maintainers navigate a very different world. Resources across tools, people, and time are afforded differently so we take on the lens of MGV when trying to adapt DevSecOps thats accessible in the projects that fuel our development heartbeats - open source.This is an exploration of the accessibility of securing open source as discussed at the [Open Summit](https://www.google.com/url?q=https://github.blog/2022-01-13-open-source-software-security-summit-securing-the-worlds-code-together/&sa=D&source=docs&ust=1643128107559411&usg=AOvVaw2LhkW5ITtzK4rngXaezpe3) at the White House earlier this year.

We plan to use [Minimum Viable Governance framework](https://static1.squarespace.com/static/556340ece4b0869396f21099/t/59d66ab28fd4d2226f13aa70/1507224246417/Minimum_Viable_Information_Risk_Management_Program.pdf) so that security across user policies, infrastructure, appsec, app structure, data, and open source collaboration can scale seamlessly with the least amount of overhead. 

**User personas:**
Although we have maintainers that will work on this project that understand enterprise architecture, a majority of users will be bootcamp students where this is their first open source project and might still be learning concepts like CI/CD and DevSecOps. 

Today we use Actions to perform administrative automations, CI/CD, and use it for CodeQL (in pink) 
<img width="1279" alt="Screen Shot 2022-04-19 at 8 41 22 AM" src="https://user-images.githubusercontent.com/9143339/164042620-b4223dbe-39af-4b85-820e-c5bf55d2498b.png">

- [Current workflows](https://github.com/ProgramEquity/amplify/actions)
  - checks formatting
  - Lint code
  - Lint workflows
  - Scorecards
  - CodeQL
  - Integration tests

## Spec/Exit Criteria
Here is an outline of what a security strategy can be like across the SDLC, so far our workflows cover up to SAST. Currently no artifacts are shipped. 
- What changes can be added to the default security policy to better engagement by maintainers?
- What potential actions could be added to this workflow? 
- Are there container specs that are needed?
- Should we be adding any external lints for Docker?
- Would we like to improve [reporting on CI](https://github.com/ProgramEquity/amplify/pull/153)
<img width="1293" alt="Screen Shot 2022-04-19 at 8 43 43 AM" src="https://user-images.githubusercontent.com/9143339/164043050-8c3f0386-6537-40b3-a0ae-bf50dc8e90dc.png">

## References
- [Existing Security MD ](https://github.com/ProgramEquity/amplify/blob/main/SECURITY.md)
- Potential actions to add:  
  - [DAST: Mayhem API](https://github.com/ProgramEquity/amplify/issues/130)
  - [Docker Lint](https://github.com/marketplace/actions/docker-lint)
  - [Megalinter](https://megalinter.github.io/latest/)
- [Past discussions](https://github.com/ProgramEquity/amplify/discussions/61)

## List subtasks here: 
- [ ] [Get ESLint working for Vue](https://github.com/ProgramEquity/amplify/issues/89)
- [ ] [Improve precommit lint](https://github.com/ProgramEquity/amplify/issues/80)

**Comment by JamesMGreene** [comment]
FWIW, we do already have a basic security policy in place today: https://github.com/ProgramEquity/amplify/security/policy

Its content is controlled by this file: https://github.com/ProgramEquity/amplify/blob/main/SECURITY.md
