### ISSUE TITLE
Hack Pod: Enhance Dev Experience via Codespaces + Secure Workflows 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#19]
⬇️ **Table of Contents:** 
- [User Story: Who does this Affect](#user-story)
- [Current Contribution Flow and Actions Checklist](#workflow)
- [Codespaces Specs and Tasks](#codespaces)
- 💻[Project view](https://github.com/orgs/ProgramEquity/projects/8)

## User Story <a id = "user-story"> </a>
<img width="510" alt="Screen Shot 2022-04-14 at 2 49 53 PM" src="https://user-images.githubusercontent.com/9143339/163482322-539fbcfc-6523-4b62-9b4b-decadb3f52b6.png">

=- Our goal is to enable students towards enterprise architecture while making their onboarding painless 

## [Current Contribution Flow and Actions](https://github.com/ProgramEquity/amplify/discussions/61) <a id = "workflow"> </a>
Today we use Actions to perform administrative automations, CI/CD, and use it for CodeQL (in pink)

![image](https://user-images.githubusercontent.com/9143339/195364390-e9dc0efd-0ea4-4d5e-a2e5-9c0666822349.png)

- [Current workflows](https://github.com/ProgramEquity/amplify/actions)
  - checks formatting
  - Lint code
  - Lint workflows
  - Scorecards
  - CodeQL
  - Integration tests

### Considerations 
- set up default container configuration
- Adding additional features to your `devcontainer.json` file
- How can we make it easier for outside collaborators that are new to open source provide their own API keys as secrets in order for the environment variables in codespaces to work? 
  - Currently, this creates a barrier for new students who also have to learn concepts of APIs keys, and secrets for each API we use by going to each  (4: Lob, Auth0, Google Civic, Stripe). What strategies do we want to have for people to route Auth0 (Even if the create their own key, how do we allow for that as a variable?
  - In particular, Auth0 callback is hard to configure for codespaces domains without each contributor having to create their own Auth0 account
- Are there container specs that are needed?
- Should we be adding any external lints for Docker?
- Bonus: what gaps can the readme fill?

**Resources:** 
- [Try out our reference](https://github.com/ProgramEquity/amplify-back-end/pull/132)
- [Contribution Guide](https://github.com/ProgramEquity/amplify/blob/main/.github/CONTRIBUTING.md)
- [GitHub Docs on Codespaces](https://docs.github.com/en/codespaces)
- [Audit ](https://github.com/ProgramEquity/amplify/discussions/61#discussioncomment-2113568)by Security Research team

**Comment by JamesMGreene** [comment]
I'm not so sure there is anything left to be done for this as of now, at least not without getting more feedback from the frontend devs on their experiences trying to use our Codespace configuration for their development.

One related task that I suspect would help their experience:
- #86

**Comment by manishapriya94** [comment]
4/1: 
- What strategies do we want to have for people to route Auth0 (Even if the create their own key, how do we allow for that as a variable?)

**Comment by eprice555** [comment]
[Post cat gif for push](https://github.com/ruairidhwm/action-cats) has issues running due to Node.js 12 being deprecated:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: abeyuya/actions-mention-to-slack
```

The fix would be using Node 16 [here](https://github.com/ruairidhwm/action-cats/blob/309530f7a011f12e0359514d2c1bb9cef114dd41/action.yml#L10) but since its not owned on our end I'll have to figure out whats the best way forward unless someone has feedback on a work around. Also this action isn't mission critical so not a priority
