### ISSUE TITLE
Insight into how many requests we are currently making to the google API.

### ISSUE THREAD

**Issue by gdomingu** [ProgramEquity/amplify#282]
This will be helpful info to know when switching over to cicero which has a different pricing model. 

@manishapriya94 would you be able to log into our google apis account and give us some numbers on how many credits/requests we are making?

**Comment by manishapriya94** [comment]
Hi @BeeXiong, blast from the past - would you still have access to this info?

**Comment by gdomingu** [comment]
Closing this as it seems we do not have access to this info anymore.
