### ISSUE TITLE
Batch: Provide photos (and more info) for representatives

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#29]
We are currently using the Google Civic API to look up relevant state and federal representative information based on the user's address. This works very well! 🎉 

However, the Civic API is also missing quite a bit of information about those representatives, often including their photos and sometimes even information contact information. 😭 

One strategy that we could employ to workaround this shortcoming is to stitch the information provided by the Google Civic API with information provided by other public APIs, such as the Open States database: https://docs.openstates.org/api-v3/ 🔀 

I'm unsure of its completeness (it seems pretty thorough at first glance) but it's definitely _better_ than relying on just the incomplete information from the Google Civic API. 😓

**Comment by manishapriya94** [comment]
@JamesMGreene We should have 5250 credits now and they do use up **one credit for each of these calls**: 
<img width="719" alt="Screen Shot 2022-03-10 at 9 49 51 AM" src="https://user-images.githubusercontent.com/9143339/157725459-cbd6032d-6e39-46cb-a501-0e83148efbe1.png">

The secret is CICERO_KEY and the base url to call is: https://cicero.azavea.com/v3.1

**Comment by gdomingu** [comment]
It sounds like from discussion today we want to move forward with switching over to Cicero api in order to get images.

**Comment by ahn-nath** [comment]
@manishapriya94 

Why isn't this issue closed?

**Comment by paramsiddharth** [comment]
> @manishapriya94
> 
> Why isn't this issue closed?

@ahn-nath Hmmm... This is a research thread, so we can probably close it. Still, I think part of this issue might correspond to #399, in which case it seems more appropriate to keep it open.
