### ISSUE TITLE
Add pictures of representatives into what search_rep returns 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#291]
Part of #270.

## Goal
<img width="336" alt="Screen Shot 2022-08-10 at 6 52 34 AM" src="https://user-images.githubusercontent.com/9143339/183918742-99c59e0a-a168-435a-9ea3-d73c6898f436.png">

In [search_rep](https://github.com/ProgramEquity/amplify/blob/main/src/components/SearchReps.vue) we want to add pictures of representatives. 

## Background info
Within lines 84-92 within the v-card of div representatives-list 
<img width="788" alt="Screen Shot 2022-08-10 at 6 50 11 AM" src="https://user-images.githubusercontent.com/9143339/183918196-985e2ad3-976d-40d6-bf8a-5ac29427b601.png">

## To do 
- [ ] create a variable that pulls from the **photo_origin_url* attribute of [Cicero API's response object](https://cicero.azavea.com/docs/#response-objects)
- [ ] Add Style elements: [float from text](https://vuetifyjs.com/en/styles/float/), [circle images (avatars)](https://vuetifyjs.com/en/components/avatars/)

**Comment by gdomingu** [comment]
Probably ok to ignore the social media icons in the mock up for now.
