### ISSUE TITLE
Pressing enter in the postal code form refreshes page

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#293]
# Pressing enter in the postal code form refreshes page

![image](https://user-images.githubusercontent.com/30315706/183913463-f98b5784-c773-4d2f-9937-1895224da2d6.png)

After writing the postal code, it is user-tendency to press enter and expect the form to submit itself.

However, it doesn't happen right now, because the submit behaviour has only been attached to the button
and not the form. The submission behaviour of the form needs to be modified.

## Refer
- [SearchReps.vue: Form](https://github.com/ProgramEquity/amplify/blob/main/src/components/SearchReps.vue#L9-L16)
- [SearchReps.vue: Submission Behaviour](https://github.com/ProgramEquity/amplify/blob/main/src/components/SearchReps.vue#L73-L81)

## Possible Solution
- The `on-submit` property of the `v-form` needs to recreate the `on-click` behaviour exhibited by the submit button.
- For event `e`, `e.preventDefault()` needs to be called to prevent the default form submission behaviour i.e. Making a request to the current route with the data, which causes the page refresh.

**Comment by paramsiddharth** [comment]
@tdo95 Hey Tee! While Sam works on the front-end part of #360, instead of waiting, we decided to assign you this simple front-end related issue to work on. :) Let me know if you have any trouble understanding what to do.

**Comment by tdo95** [comment]
Sure, I will start working on this (: @paramsiddharth
