### ISSUE TITLE
Bug title of Organization in card wraps strangely

### ISSUE THREAD

**Issue by gdomingu** [ProgramEquity/amplify#298]
## Expected Behavior

Probably should wrap on word.
<img width="806" alt="Screen Shot 2022-08-17 at 1 51 33 PM" src="https://user-images.githubusercontent.com/4443635/185240697-ef642224-c7a9-45e6-9fc9-b7b433e1133f.png">

## Current Behavior
Wraps on character.
<img width="804" alt="Screen Shot 2022-08-17 at 1 44 37 PM" src="https://user-images.githubusercontent.com/4443635/185239692-afc95073-5ae5-442a-8fa3-8d7bb0330a77.png">

## Possible Solution
Update the css of the `.v-card__title` to be
```
    align-items: left;
    font-size: 1.25rem;
    font-weight: 500;
    letter-spacing: .0125em;
    line-height: 2rem;
    text-align: left;
```

## Steps to Reproduce

1. Go to https://amplify-app-production.herokuapp.com/
2. Look at cards with long titles

## Labels 
Please add the following labels dependent on the bug type 
- Security Bug: Creates an issue that can cause harm 
- Vulnerability Bug: Creates an issue to update a supply chain dependency error
- Functional Bug: something that is causing a crash of the app

**Comment by paramsiddharth** [comment]
I think this has already been done.
