### ISSUE TITLE
Extract CSS in the representative card and use classes instead of inline styling

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#331]
# Extract CSS in the representative card and use classes instead of inline styling
The representative card component in the `cicero-api-new` branch temporarily
uses inline styling for many components.

```vue
...
  >
    <v-card-title v-text="member.name"></v-card-title>
    <v-card-subtitle v-text="member.title" style="text-align: left">  <--------
    </v-card-subtitle>
    <v-img
      style="text-align: left; border-radius: 50%; margin-left: 10px"  <--------
      v-bind:src="member.photoUrl"
      height="75"
      width="75"
    >
    </v-img>
    <v-card-subtitle
      v-text="member.address_city"
      style="text-align: left"  <--------
    ></v-card-subtitle>
...
```

## Solution
- Write CSS in the `style` tag and use classes for styling instead of inline styling.
- If Vuetify CSS helpers can be used in place of adding custom CSS, that would be preferred and reduce repetition.

**Comment by tdo95** [comment]
Hey @paramsiddharth I have opened a draft PR #352 for this issue. Take a look when you can.
