### ISSUE TITLE
Fix the display of the filter in the campaign page form

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#332]
# Fix the display of the filter in the campaign page form
The filters are often overlapped by the submit button.

![image](https://user-images.githubusercontent.com/30315706/195389184-c600c7cc-c3f1-45b6-a50b-4556576dc178.png)

## Solution
- Update the styling in the relevant components to avoid the elements overlapping.
- Test out the update on different Windows sizes and device modes (using the browser inspection tool).

**Comment by paramsiddharth** [comment]
@ahn-nath 
![image](https://user-images.githubusercontent.com/30315706/196694025-531b93a4-d1ea-4faf-808f-29ed0d6b86c3.png)
Tip: Instead of writing "Issue: #332" like you did, you can write "Resolves #332" or "Closes #332" to automatically link the PR to the issue so that the issue gets closed once the PR is merged. More on that here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by ahn-nath** [comment]
> @ahn-nath ![image](https://user-images.githubusercontent.com/30315706/196694025-531b93a4-d1ea-4faf-808f-29ed0d6b86c3.png) Tip: Instead of writing "Issue: #332" like you did, you can write "Resolves #332" or "Closes #332" to automatically link the PR to the issue so that the issue gets closed once the PR is merged. More on that here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Awesome!
