### ISSUE TITLE
Make the campaign page responsive for mobile devices

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#334]
# Make the campaign page responsive for mobile devices
Besides the campaign page having too much margin/padding on mobile devices, there also a bug related to the "Send letter" button that causes it to expand beyond the viewport on mobile devices.

Fix the styling to improve the responsive experience.

![image](https://user-images.githubusercontent.com/30315706/195396659-576fe8b3-283e-448f-bff2-85231c657636.png)

## Checklist
- [ ] Reduce the margins + padding for mobile devices.
- [ ] Fix the display issue with the “Send the letter” button once a representative is selected.

**Comment by sammychinedu2ky** [comment]
I would work on this

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky Sure, Samson. :) Good to see you take this up!

thanks @paramsiddharth

**Comment by sammychinedu2ky** [comment]
@paramsiddharth  for some reason I don't know why the input form does nothing when I input 11211 as postal code. 
From my network tab it seems to return 500 and there are some errors on the server.

**Comment by paramsiddharth** [comment]
@sammychinedu2ky You'll need to add the Cicero API key in there for it to work. @ahn-nath can help you out with this, she's done it before.

**Comment by sammychinedu2ky** [comment]
ooh ok thanks
