### ISSUE TITLE
create a user input textbox: takes merge_variable for Lob API method create_letter

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#370]

**Comment by sammychinedu2ky** [comment]
Hi @manishapriya94 
Please can you give me  lob template I am to use and also the merge variables I should use for the optional message

**Comment by paramsiddharth** [comment]
> Hi @manishapriya94 Please can you give me lob template I am to use and also the merge variables I should use for the optional message

@sammychinedu2ky I think we plan on doing that later, once we have received those details from the team that makes those decisions. :) For now, just add a text box and send its contents to the back-end in the request that is made under a customized property of any semantic name you'd like. Later, we can proceed to use a merge variable in the back-end.

**Comment by sammychinedu2ky** [comment]
Ok cool would do that 🙌

**Comment by sammychinedu2ky** [comment]
Please which end point should the request be made to @paramsiddharth

**Comment by paramsiddharth** [comment]
@sammychinedu2ky Look at the `/createLetter` endpoint in [lob.js](https://github.com/ProgramEquity/amplify/blob/main/server/routes/api/lob.js).

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky Look at the `/createLetter` endpoint in [lob.js](https://github.com/ProgramEquity/amplify/blob/main/server/routes/api/lob.js).

I saw that but that end point seems to require payment

**Comment by manishapriya94** [comment]
We need to take user input and pass it as {{constituent_input}}

![Image](https://user-images.githubusercontent.com/9143339/199857599-405af57d-c42b-430d-8651-35f198b523f5.png)

**Comment by sammychinedu2ky** [comment]
Thanks, @manishapriya94, It also requires the paymentintentId which I think can be gotten after payment is completed (having access to a test card would help). Also, I've been having issues authenticating with Auth0 on Codespaces

**Comment by paramsiddharth** [comment]
> > @sammychinedu2ky Look at the `/createLetter` endpoint in [lob.js](https://github.com/ProgramEquity/amplify/blob/main/server/routes/api/lob.js).
> 
> I saw that but that end point seems to require payment

@sammychinedu2ky Yes, you are right. It requires payment. But you can make fake test payments during development using test card numbers. Here: https://stripe.com/docs/testing

**Comment by sammychinedu2ky** [comment]
Ok thanks 🙌 @paramsiddharth

**Comment by sammychinedu2ky** [comment]
@paramsiddharth Stripe isn't currently available in my country.
