### ISSUE TITLE
Onboard Sogorea 'Te

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#374]
- [x] add letter and provide template id
- [x] deploy as a different standalone campaign page 
  - [x] with google civic api version 
- [x] add the following to carousel 
District 1: Rashi Kesarwani, up for re-election 2022, (510) 981-7110, rkesarwani@CityofBerkeley.info
District 2: Terry Taplin, (510) 981-7120, ttaplin@CityofBerkeley.info
District 3: Ben Bartlett, (510) 981-7130, bbartlett@CityofBerkeley.info
District 4: Kate Harrison, up for re-election 2022, (510) 981-7140, kharrison@CityofBerkeley.info
District 5: Sophie Hahn, (510) 981-7150, shahn@CityofBerkeley.info
District 6: Susan Wengraf, (510) 981-7160, swengraf@CityofBerkeley.info
District 7: Rigel Robinson, up for re-election 2022, (510) 981-7170, rrobinson@CityofBerkeley.info
District 8: Lori Droste, retiring 12/22, (510) 981-7180, ldroste@CityofBerkeley.info

**Comment by manishapriya94** [comment]
Template id: tmpl_7aaf42aada49f44

**Comment by DietBepis1** [comment]
The Sogorea 'Te campaign does not appear have an entry in our database for either development or production. What is the method for adding it?

**Comment by manishapriya94** [comment]
[Figma file ](https://www.figma.com/file/46c9cmuTiCpFA4DHB8OK0H/Amplify-User-Interface-%2B-Design-Guide?node-id=1622%3A629&t=mBZkGYA8T79TM6v7-0)to copy text and styling out of. Added picture assets [here. ](https://github.com/ProgramEquity/amplify/tree/main/src/assets/images)

<img width="562" alt="Screen Shot 2022-11-22 at 12 44 48 AM" src="https://user-images.githubusercontent.com/9143339/203267764-20927519-13d9-4920-a0ca-49d49115651e.png">

**Comment by manishapriya94** [comment]
let me know which branch and I'll have amplifyadvocacy.org point to it

**Comment by manishapriya94** [comment]
- [ ] add social links 
   - [ ] twitter button: https://twitter.com/programequity
   - [ ] facebook button: https://www.facebook.com/savetheshellmound
   - [ ] linkedin button: www.linkedin.com/company/programequity/
   - [ ] instagram button: https://www.instagram.com/passthepolicy/
- [ ] delete home page 
- [ ] replace shellmound logo image with aunty corinna 
https://files.slack.com/files-pri/T014R9KDASE-F04C760NSP8/image.png
- [ ] update copy in second page (replace reducing 50% emissions copy)
Indigenous communities steward more than 80% of the world's biodiversity. Returning Shellmounds means endangered species like the Condor and Salmon can return, trees like the Madrone and Mugwort can return. Our strongest strategy towards lowering carbon emissions is Indigenous led conservation of biodiversity
- [ ] add email collection ([api docs](https://docs.lob.com/#tag/Addresses/operation/addresses_list))
![image](https://user-images.githubusercontent.com/9143339/203845363-6114342b-46be-4967-a273-59cda32971a2.png)

**Comment by tried-again** [comment]
- [ ] Add a hover-state for each City Council member - to indicate those are clickable, and that clicking on one of them is required to move to the next step
- [ ] Change the subtext in Step 1 [ https://monosnap.com/file/JO6cHpW2lLJkXym6RNj2nGfj7zdJNp ] to "Let your representative know why this matters"
