### ISSUE TITLE
Reset Page Orientation on Navigation

### ISSUE THREAD

**Issue by DietBepis1** [ProgramEquity/amplify#408]
Currently, when a page is taller than a device's viewport, if a user navigates to another page (i.e. home to campaign, etc.) the viewport will remain at the coordinates of the previous page.

You may want to learn about the DOM window property.
- https://www.geeksforgeeks.org/html-dom-window-document-property/
- https://renatello.com/vue-js-scroll-top/

To fix:
- [ ] Write a function to reset each page before render. 
- [ ] Test that function if necessary

**Comment by smgraywood** [comment]
Do we have example screenshots of this issue being reproduced? I want to make sure I understand what the issue is and haven't been able to reproduce on my machine.

**Comment by paramsiddharth** [comment]
> @DietBepis1 Do we have example screenshots of this issue being reproduced? I want to make sure I understand what the issue is and haven't been able to reproduce on my machine.

@smgraywood Until Glenn responds, you can try reproducing it in the following manner:
1. Scroll down while on the home page.
2. Click a campaign.
3. Notice the scroll location from the home page is retained (which is what we want to avoid).

**Comment by smgraywood** [comment]
Thank you @paramsiddharth , that helped me a lot! Ok, I submitted a fix: https://github.com/ProgramEquity/amplify/pull/480

**Comment by smgraywood** [comment]
This issue has been resolved: https://github.com/ProgramEquity/amplify/pull/480
