### ISSUE TITLE
[Documentation] Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by therzka** [ProgramEquity/amplify#409]
We should add a CODE_OF_CONDUCT.md file at the root of the repo

see an example here: https://github.com/therzka/OSS-Example-Repo/blob/main/CODE_OF_CONDUCT.md

other resources:
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project
- https://www.valamis.com/hub/code-of-conduct#:~:text=code%20of%20conduct-,What%20is%20a%20code%20of%20conduct%3F,from%20staff%20within%20an%20organization.

**Comment by smgraywood** [comment]
Hey @coderlore sorry if I stepped on your toes on this.
