### ISSUE TITLE
Make `npm` scripts cross-platform

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#430]
# Make `npm` scripts cross-platform
Several scripts that use runtime environment variable initialization (`VAR=value cmd arg1 arg2`) would not work on Windows, and we've learnt that a number of our contributors are not necessarily Macintosh and Linux users but Windows users. Hence, this update is supposed to ease running the `npm` scripts for them.

## Scripts Affected
- `"dev:backend": "PORT=5000 nodemon -w ./server server/server.js"`
- `"lint": "DEBUG=eslint:cli-engine eslint --fix ."`
- `"lint:check": "DEBUG=eslint:cli-engine eslint ."`

## Note
[`cross-env`](https://www.npmjs.com/package/cross-env) is worth checking out. I've used it before for this particular cross-platform fix and it is pretty convenient and efficient.

**Comment by dmilburn** [comment]
curious - why is this necessary inside of a codespace? do you also want to support outside of a codespace?

**Comment by dmilburn** [comment]
we're currently working on making the codespaces experience more seamless and with a higher core count which should hopefully make it so this issue doesn't feel needed so we're going to punt on this one for now.

**Comment by paramsiddharth** [comment]
> curious - why is this necessary inside of a codespace? do you also want to support outside of a codespace?

Hey Debbie! Apparently so, that was part of the discussion in the previous few cohorts. Codespaces aren't completely reliable and much of the big stories take a local development setup to develop, so it is only on us to make it easier to set up fresh development environments locally as well.
