### ISSUE TITLE
[Needs investigation] Social media icon links not working

### ISSUE THREAD

**Issue by paramsiddharth** [ProgramEquity/amplify#446]
# Social media icon links not working
The social media icons are not clickable i.e. They don't open the links that are configured.

This was supposed to be fixed by #433 but that doesn't seem to be the case.

**Comment by DietBepis1** [comment]
@paramsiddharth , you are talking about the links in the footer? I ran the main branch with our most recent changes and they all appear to be working (except that one is a Sogorea Te' link that I forgot to change back).

https://user-images.githubusercontent.com/54147446/211158351-0d47d930-8f12-4157-8969-570a3c437019.mp4

Let me know if this is not the right section to investigate.

**Comment by paramsiddharth** [comment]
> @paramsiddharth , you are talking about the links in the footer? I ran the main branch with our most recent changes and they all appear to be working (except that one is a Sogorea Te' link that I forgot to change back).
> 
>  2023-01-07.09-27-16.mp4 
> Let me know if this is not the right section to investigate.

@DietBepis1 Strange... I'm confident I checked out the branch, ran the application, and tried clicking the icons and they didn't work. Let me check once more.

**Comment by DietBepis1** [comment]
@paramsiddharth, at the risk of stating something obvious, did you pull the changes into main? 😜

**Comment by paramsiddharth** [comment]
> @paramsiddharth, at the risk of stating something obvious, did you pull the changes into main? 😜

@DietBepis1 Noooo... I'm sure I didn't. I checked out your PR branch using [GitHub CLI](https://cli.github.com/manual/gh_pr_checkout), which is what I always do when testing PRs on GitHub.

**Comment by davidchapuis** [comment]
Hi guys, it works here too.

**Comment by paramsiddharth** [comment]
Closing as mistaken.
