### ISSUE TITLE
Updating the Campaign Model

### ISSUE THREAD

**Issue by DietBepis1** [ProgramEquity/amplify#449]
To accommodate the addition of Single Campaign Mode, we need to add some fields to Campaign. The new schema will be something like:

```
{
  "campaign": {
    "id": 1,
    "organization": "Sogorea Te' Land Trust",
    "name": "Sogorea Te' Land Trust",
    "cause": "Civic Rights",
    "type": "Grant",
    "page_url": "[www.thebreatheact.org](https://sogoreate-landtrust.org/)",
    "campaign_tagline": "Protect Our Sacred Shellmounds",
    "campaign_text": "Lorem ipsum dolor sit amet.....",
    "supplemental_text": "Some other text blurb that appears on the search reps page"
  }
```

This will simplify our configuration when deploying Amplify for a single campaign.

**Comment by paramsiddharth** [comment]
@DietBepis1 Hi Glenn, I have a question. Will the updated schema apply to all the campaigns in the campaigns table, or just to a single campaign in a separate table?

**Comment by DietBepis1** [comment]
I was planning to add nullable fields to the current model, but would be open to discussing other options if you have an idea.

**Comment by smgraywood** [comment]
Hi @DietBepis1 ! I updated the schema to reflect the requested changes. Are we getting rid of the logo_url, letters_goal and donation_goal fields? Also does this need to be linked up with anything in the frontend or are we just updating this schema for this ticket?

**Comment by paramsiddharth** [comment]
@smgraywood Awaiting confirmation from @DietBepis1, but I believe directly editing the migration is not how we should do this. We need to create a new migration using the [stub](https://github.com/ProgramEquity/amplify/blob/main/server/db/_migration.stub.js) and update it to add/remove and modify columns and/or types as needed.
