### ISSUE TITLE
Onboard group 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#490]
Any chance we can launch by 15th?
Location: Seattle, WA
Name: Equality Labs
Cause: Civic rights 

Council: 
![image](https://user-images.githubusercontent.com/9143339/218234893-8e6dcd94-25dc-4885-8c78-dfd199fa48c5.png)
https://www.seattle.gov/cityclerk/agendas-and-legislative-resources/find-your-council-district

Letter: tmpl_827a50ffb23b7d5

**Comment by DietBepis1** [comment]
Will this be another single-campaign feature?

**Comment by manishapriya94** [comment]
yes!

**Comment by DietBepis1** [comment]
That should be doable then. When you have a chance, send me any images/copy for their deployment. The big thing is resolving the Stripe bug, but I have an idea of what needs to be done now so we'll see how long that takes. At the very least, I should be able to stop the auto-refunding, even if that means some manual reconciliation later.

**Comment by manishapriya94** [comment]
@nawazkhan any ideas on the stripe bug?
@DietBepis1 would you like me to mockup on figma?

**Comment by DietBepis1** [comment]
@manishapriya94, sure, that'd be great!

For Stripe, I think the plan of attack is to create a fufillment endpoint that does our book-keeping and sends the letter, instead of the front-end controlling that part. Working on a solution now.

Here's the Stripe doc for reference if you all are interested: https://stripe.com/docs/payments/checkout/fulfill-orders

**Comment by manishapriya94** [comment]
Here is the UI for front page
https://www.figma.com/file/46c9cmuTiCpFA4DHB8OK0H/Amplify-User-Interface-%2B-Design-Guide?node-id=3710%3A4132

It wasn't letting me add text so I added in the comment: 
On Jan. 24, Seattle City Councilmember Kshama Sawant announced at a press conference at City Hall new legislation to prohibit caste-based discrimination in the city of Seattle. If passed, the ordinance would add caste to the city’s list of protected classes, outlawing discrimination in employment, housing, public places and contracting. It would also empower the Seattle Office for Civil Rights to investigate complaints of caste discrimination and facilitate a settlement for monetary damages or other forms of recompense.

Last May, [Real Change reported that caste remains a hidden and underreported issue](https://www.realchangenews.org/news/2022/05/18/hidden-discrimination-casteism-persists-south-asian-spaces) among South Asian communities in the Seattle area. In recent years, anti-caste advocates have won important victories in the United States, such as [California’s 2020 lawsuit against megacorporation Cisco](https://www.reuters.com/article/us-cisco-lawsuit/california-accuses-cisco-of-job-discrimination-based-on-indian-employees-caste-idUSKBN2423YE) for caste-based discrimination and the recognition of caste as a protected status [by the California State University system in 2022](https://www.latimes.com/california/story/2022-01-20/csu-adds-caste-to-its-anti-discrimination-policy).

**Comment by manishapriya94** [comment]
Updated letter number: tmpl_827a50ffb23b7d5
