### ISSUE TITLE
User input office_div filter 

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/amplify#51]
# Purpose: Have reps be filterable by jurisdiction: federal, state, county
<img width="900" alt="Screen Shot 2021-05-22 at 6 18 28 PM" src="https://user-images.githubusercontent.com/9143339/119244978-699f4c00-bb2a-11eb-97a2-e22995835135.png">

User Story: 
- Use button to filter representatives and shorten returned list of search for easier viewing

Tasks: 
1. Create buttons in campaign.vue view 
2. Have button filter by representative [levels](https://developers.google.com/civic-information/docs/v2/representatives/representativeInfoByAddress)
   a. country = **federal** 
   b. level 1 = **state**
   c. level 2 = **county** 
3. Only show representative array that corresponds 

File to change: [SearchReps](https://github.com/ProgramEquity/amplify/blob/main/src/components/SearchReps.vue) line 17

**Comment by serunkuma** [comment]
all requests on this issue are on the google civic api
