### ISSUE TITLE
Create Admins Table

### ISSUE THREAD

**Issue by DietBepis1** [ProgramEquity/amplify#600]
### Description
A key thing that the campaign control panel feature introduces is the idea of an authenticated user, i.e. someone who logs in with credentials and has privileges that a casual app visitor lacks. This issue is for creating an `admins` table.

### Spec
The data structure should be something like
| field_name | type  |
|----------------|--------|
| first_name | **string** not null |
| last_name | **string** not null |
| user_name (or email?) | **string** not null |
| password | encrypted **string** not null |
| active | **boolean** not null |
| last_login_at | Date |

What other fields do _you_ think should be added to make this a flexible data structure?

**TIP: You can use `knex` to auto-create an id and timestamps with**
```
table.increments('id')  https://knexjs.org/guide/schema-builder.html#increments
table.timestamps()      https://knexjs.org/guide/schema-builder.html#timestamps
```

### Copilot Prompts
`Explain how to create a Postgres column for password data?`
`Create a knex migration that adds a table called 'admins'`
`Explain a how to an ORM works`

**Comment by beverand** [comment]
Last login time will help with audit

**Comment by DietBepis1** [comment]
That's an excellent idea.

**Comment by ktrudickm** [comment]
I see this issue is already assigned but is it ok if I join on this issue too? @DietBepis1 @E-wang42

**Comment by kalahasv** [comment]
@E-wang42 Hi, Is it ok if I work on this as well?

**Comment by E-wang42** [comment]
sorry didn't get a chance to reply.  not sure how many people we can have on a single task.  maybe we can talk about it in Slack

**Comment by JulieGunawan** [comment]
@E-wang42 @ktrudickm  Can I help out on this one too?

**Comment by DietBepis1** [comment]
@E-wang42, @ktrudickm, @JulieGunawan This is an issue I envisioned a single person working on because it is a singular task, however I am happy for you to all collaborate. You could either all submit some commits in one branch, or come up with separate solutions and I can figure out how to give you each credit for working on it.
