### ISSUE TITLE
Add Vetur VSCode extension to Codespaces extension list

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#86]
We should add the [Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) `Vue.volar` Vue VSCode extension to Codespaces extension list to make it easier to work with Vue from a Codespace.

**Comment by cwndrws** [comment]
It seems that there is a new official vue extension: [Vue.volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar). I'm updating the issue body to reflect this change.
